### PR TITLE
Set up publishing to gradle

### PR DESCRIPTION
**Pull request by dansanduleac**

### CODE REVIEW

**Review by iamdanfox — APPROVED** [review]
LGTM - let's just wait until Gradle approves our request and this actually publishes!

**Comment by derenrich** [comment]
bump on this? it's blocking a plugin I'm writing

**Comment by dansanduleac** [comment]
@derenrich I couldn't figure out a way to publish multiple jars through gradle's plugin (we need to publish the api jar to the same repo somehow, since it's a dependency of the plugin jar).
Either we get rid of the API jar (which is currently being used internally), or this is impossible.

**Comment by iamdanfox** [comment]
Closing out stale PR

**Pull request closed without merging**
