### PR TITLE
Improvement: Bring back generateNpmrc with full configurability

### PR DESCRIPTION
**Pull request by robert3005**
## After this PR

==COMMIT_MSG==
Provide unopinionated task for generating npmrc that lets users publish conjure clients to their npm repos
==COMMIT_MSG==

### CODE REVIEW

**Comment by robert3005** [comment]
Ping, it's been 3 weeks

**Comment by robert3005** [comment]
ping

**Comment by fawind** [comment]
Previous PR for reference: https://github.com/palantir/gradle-conjure/pull/1025

**Comment by fawind** [comment]
Will update our internal publishing plugin to use this and also excavator to also update the internal publishing plugin when updating gradle-conjure.

**Review by fawind — APPROVED** [review]

**Pull request merged**
